# See also https://pre-commit.com/hooks.html
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-toml
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: fix-byte-order-marker
    -   id: fix-encoding-pragma
    -   id: trailing-whitespace
# reformat python code
-   repo: https://github.com/psf/black
    rev: 21.4b2
    hooks:
    -   id: black
# reorder python imports
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.3.6
    hooks:
    -   id: reorder-python-imports
        args: [--py37-plus]
# remove unused imports or variables
-   repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
    -   id: autoflake
        args:
        -   --in-place
        -   --remove-unused-variables
# format *.yaml files
-   repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.0.0
    hooks:
    -   id: pretty-format-yaml
        args:
        -   --autofix
        -   --indent
        -   '4'
        -   --preserve-quotes
# fix style of *.md files
-   repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.26.0
    hooks:
    -   id: markdownlint
        args:
        -   --fix
